### PR TITLE
Separate OS-Dependent code from OS-Independent code

### PR DESCRIPTION
**Pull request by KrazyKirby99999**
Previously, there were three different versions of scout.py, a windows version, and two linux versions. The code that works for both operating systems is combined, and the code that is unique to each operating system is separate, resulting in much cleaner and easier to maintain code.

### CODE REVIEW

**Comment by KrazyKirby99999** [comment]
These changes will need to be tested.

**Review by leifadev — APPROVED** [review]
lets try this

**Comment by leifadev** [comment]
later i will review this and try to implement it, thanks!

**Review by leifadev — APPROVED** [review]

**Comment by KrazyKirby99999** [comment]
I resolved the conflicts. You may have to reimplement more recent additions to scout.py, although that should be simple because you can view the commit history.

**Review by leifadev — APPROVED** [review]

**Review by leifadev — APPROVED** [review]

**Review by leifadev — APPROVED** [review]

**Review by leifadev — APPROVED** [review]

**Pull request merged**
